name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release /p:EnvironmentName=Production --no-restore
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -o "blog" --framework net6.0 --runtime linux-x64 /p:EnvironmentName=Production --no-self-contained
    - name: Compress Release
      run: tar czvf "blog.tar.gz" "blog"
    - name: Save Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: blog
        path: blog.tar.gz
        if-no-files-found: error
