# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v2.1.0
      with:
        name: artifact
        path: ~/artifact
    - name: Copy Artifact to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        source: "/home/runner/artifact"
        target: "/var/www/blog/staging/"
        rm: true
    - name: Deploy Artifact on Server
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          whoami
